stages:
  - lint
  - security
  - test

# Linting: run Black and Ruff
lint:
  stage: lint
  image: python:3.13
  before_script:
    - pip install black ruff
  script:
    - black --check --config ./pyproject.toml $(find src tests -type f -name '*.py')
    - ruff check --fix $(find src tests -type f -name '*.py')

# Security: run Bandit
security:
  stage: security
  image: python:3.13
  before_script:
    - pip install bandit
  script:
    - bandit -r src tests

# Testing: run Pytest with Coverage
test:
  stage: test
  image: python:3.13
  before_script:
    - pip install pytest pytest-cov # Install pytest and pytest-cov for coverage
  script:
    - pytest --maxfail=1 --disable-warnings -q --cov=src --cov=tests --cov-fail-under=80 # Run tests and check coverage with a threshold of 80%
  only:
    - main
    - develop
