repos:
  - repo: https://github.com/ambv/black
    rev: 24.3.0 # You should run `pre-commit autoupdate` to get the actual latest tag
    hooks:
      - id: black
        language_version: python3.13
        args:
          - "--config"
          - "./pyproject.toml"
        files: ^(src|tests)/.*\.(py|pyx|pyi)$
        exclude: ^(?!main$|develop$).*$ # Only allow main and develop branches

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src|tests)/.*\.(py|pyx|pyi)$
        language_version: python3.13
        exclude: ^(?!main$|develop$).*$ # Only allow main and develop branches

  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest with Coverage
        entry: bash -c 'export PYTHONPATH=$(pwd)/src && pytest --cov=src --cov-report=term-missing'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        exclude: ^(?!main$|develop$).*$ # Only allow main and develop branches

